# Generated by Django 2.1.5 on 2019-04-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='listing_realtor',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
