# Generated by Django 2.1.5 on 2019-06-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_listing_realtor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='inquiry',
        ),
    ]
