
state_choices = {
    "AL":'Alabama',
    "AK":'Alaska',
    "AZ": '"Arizona',
    "AR": 'Arkansas',
    "CA": 'California',
    "CO": 'Colorado',
    "CT": 'Connecticut',
    "DE": 'Delaware',
    "DC": 'District_Of_Columbia',
    "FL": 'Florida',
    "GA": 'Georgia',
    "HI": 'Hawaii',
    "ID": 'Idaho',
    "IL": 'Illinois',
    "IN": 'Indiana',
    "IA": 'Iowa',
    "KS": 'Kansas',
    "KY": 'Kentucky',
    "LA": 'Louisiana',
    "ME": 'Maine',
    "MD": 'Maryland',
    "MA": 'Massachusetts',
    "MI": 'Michigan',
    "MN": 'Minnesota',
    "MS": 'Mississippi',
    "MT": 'Montana',
    "NE": 'Nebraska',
    "NH": 'New_Hampshire',
    "NJ": 'New_Jersey',
    "NM": 'New_Mexico',
    "NY": 'New_York',
    "NC": 'North_Carolina',
    "ND": 'North_Dakota',
    "OH": 'Ohio',
    "OK": 'Oklahoma',
    "PA": 'Pennsylvania',
    "RI": 'Rhode_Island',
    "SC": 'South_Carolina',
    "SD": 'South_Dakota',
    "TN": 'Tennessee',
    "TX": 'Texas',
    "UT": 'Utah',
    "VT": 'Vermont',
    "VA": 'Virginia',
    "WA": 'Washington',
    "WV": 'West_Virginia',
    "WI": 'Wisconsin',
    "WY": 'Wyoming'
}

bedroom_choices = {
    "1": '1',
    "2": '2',
    "3": '3',
    "4": '4',
    "5": '5',
    "6": '6',
    "7": '7',
    "8": '8',
    "9": '9',
    "10":'10'
}

prices = {
    "150000": '150,000',
    "200000": '200,000',
    "300000": '300,000',
    "400000": '400,000',
    "500000": '500,000',
    "600000": '600,000',
    "700000": '700,000',
    "800000": '800,000',
    "900000": '900,000',
    "1000000": '1M+'
}